language: php

php:
  - '7.1'

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer global require satooshi/php-coveralls:@stable codeclimate/php-test-reporter:@stable --no-update

install:
  - composer global update --no-interaction
  - composer update --no-interaction $COMPOSER_FLAGS

script:
  - composer validate
  - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - coveralls -v
  - test-reporter
