language: php

php:
  - '7.1'

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer global require satooshi/php-coveralls:@stable phpunit/phpunit:@stable --no-update

install:
  - composer global update --no-interaction
  - composer update --no-interaction $COMPOSER_FLAGS

script:
  - composer validate
  - phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml
